version: '3.3'
services:
  mysqldb:
    image: mysql
    ports:
    - '3308:3306'
    environment: # could be hidden with docker secrets
      - MYSQL_USER=dbserviceUser
      - MYSQL_PASSWORD=dbservicePassword
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=extvaldb
    volumes:
      - './dbservice/initDatabase.sql:/docker-entrypoint-initdb.d/1.sql'
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - db_network
  dbservice:
    build:
      context: ./dbservice
      dockerfile: ./Dockerfile
    image: localhost/dbservice
    depends_on:
      - mysqldb
    ports:
    - '9091:8081'
    networks:
      - db_network
      - fdt_network
  fdtservice:
    build:
      context: ./formatdatetimeservice
      dockerfile: ./Dockerfile
    image: localhost/fdtservice
    ports:
    - '9093:8083'
    networks:
      - fdt_network
      - gdt_network
  gdtservice:
    build:
      context: ./datetimegenerator
      dockerfile: ./Dockerfile
    image: localhost/gdtservice
    ports:
    - '9094:8084'
    networks:
      - gdt_network
  adminservice:
    build:
      context: ./adminservice
      dockerfile: ./Dockerfile
    image: localhost/adminservice
    ports:
    - '9096:8086'
    networks:
      - gdt_network
    depends_on:
      - gdtservice
  kafkaservice:
    build:
      context: ./kafkaservice
      dockerfile: ./Dockerfile
    image: localhost/kafkaservice
    ports:
      - '9095:8085'
    networks:
      - kafka_service_network
      - db_network
    depends_on:
      - kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2500:2181'
    networks:
      - kafka_zookeeper_network
    volumes:
      - ./volumes/zoo/data:/opt/zookeeper-3.4.13/data
      #- ./volumes/zoo/conf:/opt/zookeeper-3.4.13/conf
  kafka:
    image: wurstmeister/kafka
    ports:
      - '2501:9092'
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      #- KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=date-time-topic:1:1
      - KAFKA_LOG_DIRS=/logs
    depends_on:
      - zookeeper
    networks:
      - kafka_zookeeper_network
      - fdt_network
      - kafka_service_network
    volumes:
      - ./volumes/kafka/logs:/logs
networks:
  db_network: {}
  fdt_network: {}
  gdt_network: {}
  kafka_zookeeper_network: {}
  kafka_service_network: {}
